# Generated by Django 2.2.3 on 2019-07-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20190713_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
